# Generated by Django 4.2.2 on 2024-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='balance',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='paid_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='paid_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
