# Generated by Django 4.2.2 on 2024-02-08 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_tokenusage_balance_tokenusage_paid_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
