# Generated by Django 4.2.2 on 2024-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_tokenusage_created_at_tokenusage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='balance',
            field=models.FloatField(default=2000.0),
        ),
    ]
