# Generated by Django 4.1.7 on 2023-05-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_mask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mask',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
