# Generated by Django 4.1.7 on 2023-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_update_at_mask_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
