# Generated by Django 4.2.2 on 2023-06-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_mask_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mask',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='mask_avatar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='mask_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
